Import('*')

if env['CONF']['BUILD_ISA']:
    SimObject('ValuePredictor.py',
        sim_objects=['BaseValuePredictor', 'LastValueVP', 'VtageVP',
                     'EVtageVP'])

    Source('base.cc')
    Source('last_value.cc')
    Source('lvp_table.cc')
    Source('vtage_tables.cc')
    Source('vtage.cc')
    Source('evtage_tables.cc')
    Source('evtage.cc')

    GTest('lvp_table.test', 'lvp_table.test.cc', 'lvp_table.cc')
    GTest('vtage_tables.test', 'vtage_tables.test.cc', 'vtage_tables.cc')
    GTest('evtage_tables.test', 'evtage_tables.test.cc', 'evtage_tables.cc')

    DebugFlag('ValuePred')
